//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum msdyn_bookingsource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Manual = 690970003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mobile = 690970002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ScheduleAssistant = 690970004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ScheduleBoard = 690970001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemAgreementSchedule = 690970005,
	}
}