//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum BookableResourceCategoryState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Resource category master used to categorize people and equipment.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bookableresourcecategory")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class BookableResourceCategory : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string BookableResourceCategoryId = "bookableresourcecategoryid";
			public const string Id = "bookableresourcecategoryid";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string Description = "description";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_billingtype = "msdyn_billingtype";
			public const string msdyn_targetutilization = "msdyn_targetutilization";
			public const string msdyn_TransactionCategory = "msdyn_transactioncategory";
			public const string Name = "name";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string business_unit_bookableresourcecategory = "business_unit_bookableresourcecategory";
			public const string lk_bookableresourcecategory_createdby = "lk_bookableresourcecategory_createdby";
			public const string lk_bookableresourcecategory_createdonbehalfby = "lk_bookableresourcecategory_createdonbehalfby";
			public const string lk_bookableresourcecategory_modifiedby = "lk_bookableresourcecategory_modifiedby";
			public const string lk_bookableresourcecategory_modifiedonbehalfby = "lk_bookableresourcecategory_modifiedonbehalfby";
			public const string msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory = "msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory";
			public const string team_bookableresourcecategory = "team_bookableresourcecategory";
			public const string TransactionCurrency_bookableresourcecategory = "TransactionCurrency_bookableresourcecategory";
			public const string user_bookableresourcecategory = "user_bookableresourcecategory";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BookableResourceCategory() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bookableresourcecategory";
		
		public const string PrimaryIdAttribute = "bookableresourcecategoryid";
		
		public const string PrimaryNameAttribute = "name";
		
		public const int EntityTypeCode = 1147;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the resource category.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookableresourcecategoryid")]
		public System.Nullable<System.Guid> BookableResourceCategoryId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bookableresourcecategoryid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BookableResourceCategoryId");
				this.SetAttributeValue("bookableresourcecategoryid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("BookableResourceCategoryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookableresourcecategoryid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.BookableResourceCategoryId = value;
			}
		}
		
		/// <summary>
		/// lk_bookableresourcecategory_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// lk_bookableresourcecategory_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Type a detailed description of what the categorization is about.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the bookableresourcecategory with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// lk_bookableresourcecategory_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// lk_bookableresourcecategory_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Select the billing type for this resource role.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_billingtype")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_billingtype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_billingtype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_billingtype");
				this.SetAttributeValue("msdyn_billingtype", value);
				this.OnPropertyChanged("msdyn_billingtype");
			}
		}
		
		/// <summary>
		/// Enter the target usage rate for this resource role.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_targetutilization")]
		public System.Nullable<int> msdyn_targetutilization
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_targetutilization");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_targetutilization");
				this.SetAttributeValue("msdyn_targetutilization", value);
				this.OnPropertyChanged("msdyn_targetutilization");
			}
		}
		
		/// <summary>
		/// Enter the default transaction category for this resource role.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_transactioncategory")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_TransactionCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_transactioncategory");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TransactionCategory");
				this.SetAttributeValue("msdyn_transactioncategory", value);
				this.OnPropertyChanged("msdyn_TransactionCategory");
			}
		}
		
		/// <summary>
		/// Type the name of the resource category.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// owner_bookableresourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// business_unit_bookableresourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningBusinessUnit");
				this.SetAttributeValue("owningbusinessunit", value);
				this.OnPropertyChanged("OwningBusinessUnit");
			}
		}
		
		/// <summary>
		/// team_bookableresourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningTeam");
				this.SetAttributeValue("owningteam", value);
				this.OnPropertyChanged("OwningTeam");
			}
		}
		
		/// <summary>
		/// user_bookableresourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// Status of the Resource Category
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<DLaB.Xrm.Entities.BookableResourceCategoryState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((DLaB.Xrm.Entities.BookableResourceCategoryState)(System.Enum.ToObject(typeof(DLaB.Xrm.Entities.BookableResourceCategoryState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Resource Category
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// TransactionCurrency_bookableresourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcecategory_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategory_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.AsyncOperation> bookableresourcecategory_AsyncOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.AsyncOperation>("bookableresourcecategory_AsyncOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcecategory_AsyncOperations");
				this.SetRelatedEntities<DLaB.Xrm.Entities.AsyncOperation>("bookableresourcecategory_AsyncOperations", null, value);
				this.OnPropertyChanged("bookableresourcecategory_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcecategory_bookableresourcecategoryassn_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategory_bookableresourcecategoryassn_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.BookableResourceCategoryAssn> bookableresourcecategory_bookableresourcecategoryassn_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.BookableResourceCategoryAssn>("bookableresourcecategory_bookableresourcecategoryassn_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcecategory_bookableresourcecategoryassn_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.BookableResourceCategoryAssn>("bookableresourcecategory_bookableresourcecategoryassn_ResourceCategory", null, value);
				this.OnPropertyChanged("bookableresourcecategory_bookableresourcecategoryassn_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcecategory_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategory_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.BulkDeleteFailure> bookableresourcecategory_BulkDeleteFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.BulkDeleteFailure>("bookableresourcecategory_BulkDeleteFailures", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcecategory_BulkDeleteFailures");
				this.SetRelatedEntities<DLaB.Xrm.Entities.BulkDeleteFailure>("bookableresourcecategory_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("bookableresourcecategory_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcecategory_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategory_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.DuplicateRecord> bookableresourcecategory_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("bookableresourcecategory_DuplicateBaseRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcecategory_DuplicateBaseRecord");
				this.SetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("bookableresourcecategory_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("bookableresourcecategory_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcecategory_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategory_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.DuplicateRecord> bookableresourcecategory_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("bookableresourcecategory_DuplicateMatchingRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcecategory_DuplicateMatchingRecord");
				this.SetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("bookableresourcecategory_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("bookableresourcecategory_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcecategory_MailboxTrackingFolders
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategory_MailboxTrackingFolders")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.MailboxTrackingFolder> bookableresourcecategory_MailboxTrackingFolders
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.MailboxTrackingFolder>("bookableresourcecategory_MailboxTrackingFolders", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcecategory_MailboxTrackingFolders");
				this.SetRelatedEntities<DLaB.Xrm.Entities.MailboxTrackingFolder>("bookableresourcecategory_MailboxTrackingFolders", null, value);
				this.OnPropertyChanged("bookableresourcecategory_MailboxTrackingFolders");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcecategory_PrincipalObjectAttributeAccess
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategory_PrincipalObjectAttributeAccess")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess> bookableresourcecategory_PrincipalObjectAttributeAccess
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess>("bookableresourcecategory_PrincipalObjectAttributeAccess", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcecategory_PrincipalObjectAttributeAccess");
				this.SetRelatedEntities<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess>("bookableresourcecategory_PrincipalObjectAttributeAccess", null, value);
				this.OnPropertyChanged("bookableresourcecategory_PrincipalObjectAttributeAccess");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcecategory_ProcessSession
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategory_ProcessSession")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.ProcessSession> bookableresourcecategory_ProcessSession
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.ProcessSession>("bookableresourcecategory_ProcessSession", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcecategory_ProcessSession");
				this.SetRelatedEntities<DLaB.Xrm.Entities.ProcessSession>("bookableresourcecategory_ProcessSession", null, value);
				this.OnPropertyChanged("bookableresourcecategory_ProcessSession");
			}
		}
		
		/// <summary>
		/// 1:N BookableResourceCategory_SyncErrors
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("BookableResourceCategory_SyncErrors")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.SyncError> BookableResourceCategory_SyncErrors
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.SyncError>("BookableResourceCategory_SyncErrors", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BookableResourceCategory_SyncErrors");
				this.SetRelatedEntities<DLaB.Xrm.Entities.SyncError>("BookableResourceCategory_SyncErrors", null, value);
				this.OnPropertyChanged("BookableResourceCategory_SyncErrors");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcecategory_UserEntityInstanceDatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategory_UserEntityInstanceDatas")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.UserEntityInstanceData> bookableresourcecategory_UserEntityInstanceDatas
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.UserEntityInstanceData>("bookableresourcecategory_UserEntityInstanceDatas", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcecategory_UserEntityInstanceDatas");
				this.SetRelatedEntities<DLaB.Xrm.Entities.UserEntityInstanceData>("bookableresourcecategory_UserEntityInstanceDatas", null, value);
				this.OnPropertyChanged("bookableresourcecategory_UserEntityInstanceDatas");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.BookableResourceBooking> msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.BookableResourceBooking>("msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid");
				this.SetRelatedEntities<DLaB.Xrm.Entities.BookableResourceBooking>("msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_bookableresourcebookingheader_resourcecategoryid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_bookableresourcebookingheader_resourcecategoryid")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.BookableResourceBookingHeader> msdyn_bookableresourcecategory_bookableresourcebookingheader_resourcecategoryid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.BookableResourceBookingHeader>("msdyn_bookableresourcecategory_bookableresourcebookingheader_resourcecategoryid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_bookableresourcebookingheader_resourcecategoryid");
				this.SetRelatedEntities<DLaB.Xrm.Entities.BookableResourceBookingHeader>("msdyn_bookableresourcecategory_bookableresourcebookingheader_resourcecategoryid", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_bookableresourcebookingheader_resourcecategoryid");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_actual_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_actual_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_actual> msdyn_bookableresourcecategory_msdyn_actual_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_actual>("msdyn_bookableresourcecategory_msdyn_actual_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_actual_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_actual>("msdyn_bookableresourcecategory_msdyn_actual_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_actual_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_estimateline_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_estimateline_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_estimateline> msdyn_bookableresourcecategory_msdyn_estimateline_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_estimateline>("msdyn_bookableresourcecategory_msdyn_estimateline_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_estimateline_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_estimateline>("msdyn_bookableresourcecategory_msdyn_estimateline_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_estimateline_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_fact_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_fact_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_fact> msdyn_bookableresourcecategory_msdyn_fact_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_fact>("msdyn_bookableresourcecategory_msdyn_fact_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_fact_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_fact>("msdyn_bookableresourcecategory_msdyn_fact_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_fact_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_invoicelinetransaction_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_invoicelinetransaction_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_invoicelinetransaction> msdyn_bookableresourcecategory_msdyn_invoicelinetransaction_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_invoicelinetransaction>("msdyn_bookableresourcecategory_msdyn_invoicelinetransaction_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_invoicelinetransaction_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_invoicelinetransaction>("msdyn_bookableresourcecategory_msdyn_invoicelinetransaction_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_invoicelinetransaction_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_journalline_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_journalline_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_journalline> msdyn_bookableresourcecategory_msdyn_journalline_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_journalline>("msdyn_bookableresourcecategory_msdyn_journalline_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_journalline_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_journalline>("msdyn_bookableresourcecategory_msdyn_journalline_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_journalline_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_opportunitylineresourcecategory_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_opportunitylineresourcecategory_ResourceCate" +
			"gory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_opportunitylineresourcecategory> msdyn_bookableresourcecategory_msdyn_opportunitylineresourcecategory_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_opportunitylineresourcecategory>("msdyn_bookableresourcecategory_msdyn_opportunitylineresourcecategory_ResourceCate" +
						"gory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_opportunitylineresourcecategory_ResourceCate" +
						"gory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_opportunitylineresourcecategory>("msdyn_bookableresourcecategory_msdyn_opportunitylineresourcecategory_ResourceCate" +
						"gory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_opportunitylineresourcecategory_ResourceCate" +
						"gory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_opportunitylinetransaction_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_opportunitylinetransaction_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_opportunitylinetransaction> msdyn_bookableresourcecategory_msdyn_opportunitylinetransaction_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_opportunitylinetransaction>("msdyn_bookableresourcecategory_msdyn_opportunitylinetransaction_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_opportunitylinetransaction_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_opportunitylinetransaction>("msdyn_bookableresourcecategory_msdyn_opportunitylinetransaction_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_opportunitylinetransaction_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_orderlineresourcecategory_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_orderlineresourcecategory_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_orderlineresourcecategory> msdyn_bookableresourcecategory_msdyn_orderlineresourcecategory_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_orderlineresourcecategory>("msdyn_bookableresourcecategory_msdyn_orderlineresourcecategory_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_orderlineresourcecategory_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_orderlineresourcecategory>("msdyn_bookableresourcecategory_msdyn_orderlineresourcecategory_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_orderlineresourcecategory_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_orderlinetransaction> msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_orderlinetransaction>("msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_orderlinetransaction>("msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_projectapproval_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_projectapproval_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_projectapproval> msdyn_bookableresourcecategory_msdyn_projectapproval_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_projectapproval>("msdyn_bookableresourcecategory_msdyn_projectapproval_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_projectapproval_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_projectapproval>("msdyn_bookableresourcecategory_msdyn_projectapproval_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_projectapproval_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_projectparameter_projectmanagerrole
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_projectparameter_projectmanagerrole")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_projectparameter> msdyn_bookableresourcecategory_msdyn_projectparameter_projectmanagerrole
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_projectparameter>("msdyn_bookableresourcecategory_msdyn_projectparameter_projectmanagerrole", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_projectparameter_projectmanagerrole");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_projectparameter>("msdyn_bookableresourcecategory_msdyn_projectparameter_projectmanagerrole", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_projectparameter_projectmanagerrole");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_projectparameter_teammemberrole
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_projectparameter_teammemberrole")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_projectparameter> msdyn_bookableresourcecategory_msdyn_projectparameter_teammemberrole
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_projectparameter>("msdyn_bookableresourcecategory_msdyn_projectparameter_teammemberrole", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_projectparameter_teammemberrole");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_projectparameter>("msdyn_bookableresourcecategory_msdyn_projectparameter_teammemberrole", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_projectparameter_teammemberrole");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_projecttask_resourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_projecttask_resourcecategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_projecttask> msdyn_bookableresourcecategory_msdyn_projecttask_resourcecategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_projecttask>("msdyn_bookableresourcecategory_msdyn_projecttask_resourcecategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_projecttask_resourcecategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_projecttask>("msdyn_bookableresourcecategory_msdyn_projecttask_resourcecategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_projecttask_resourcecategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_projectteam_resourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_projectteam_resourcecategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_projectteam> msdyn_bookableresourcecategory_msdyn_projectteam_resourcecategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_projectteam>("msdyn_bookableresourcecategory_msdyn_projectteam_resourcecategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_projectteam_resourcecategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_projectteam>("msdyn_bookableresourcecategory_msdyn_projectteam_resourcecategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_projectteam_resourcecategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_quotelineanalyticsbreakdown_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_quotelineanalyticsbreakdown_ResourceCategory" +
			"")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_quotelineanalyticsbreakdown> msdyn_bookableresourcecategory_msdyn_quotelineanalyticsbreakdown_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_quotelineanalyticsbreakdown>("msdyn_bookableresourcecategory_msdyn_quotelineanalyticsbreakdown_ResourceCategory" +
						"", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_quotelineanalyticsbreakdown_ResourceCategory" +
						"");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_quotelineanalyticsbreakdown>("msdyn_bookableresourcecategory_msdyn_quotelineanalyticsbreakdown_ResourceCategory" +
						"", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_quotelineanalyticsbreakdown_ResourceCategory" +
						"");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_quotelineresourcecategory_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_quotelineresourcecategory_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_quotelineresourcecategory> msdyn_bookableresourcecategory_msdyn_quotelineresourcecategory_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_quotelineresourcecategory>("msdyn_bookableresourcecategory_msdyn_quotelineresourcecategory_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_quotelineresourcecategory_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_quotelineresourcecategory>("msdyn_bookableresourcecategory_msdyn_quotelineresourcecategory_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_quotelineresourcecategory_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_quotelinetransaction_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_quotelinetransaction_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_quotelinetransaction> msdyn_bookableresourcecategory_msdyn_quotelinetransaction_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_quotelinetransaction>("msdyn_bookableresourcecategory_msdyn_quotelinetransaction_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_quotelinetransaction_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_quotelinetransaction>("msdyn_bookableresourcecategory_msdyn_quotelinetransaction_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_quotelinetransaction_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_resourcecategorypricelevel_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_resourcecategorypricelevel_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_resourcecategorypricelevel> msdyn_bookableresourcecategory_msdyn_resourcecategorypricelevel_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_resourcecategorypricelevel>("msdyn_bookableresourcecategory_msdyn_resourcecategorypricelevel_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_resourcecategorypricelevel_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_resourcecategorypricelevel>("msdyn_bookableresourcecategory_msdyn_resourcecategorypricelevel_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_resourcecategorypricelevel_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_resourcerequest_roleid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_resourcerequest_roleid")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_resourcerequest> msdyn_bookableresourcecategory_msdyn_resourcerequest_roleid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_resourcerequest>("msdyn_bookableresourcecategory_msdyn_resourcerequest_roleid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_resourcerequest_roleid");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_resourcerequest>("msdyn_bookableresourcecategory_msdyn_resourcerequest_roleid", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_resourcerequest_roleid");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_rolecompetencyrequirement_resourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_rolecompetencyrequirement_resourcecategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_rolecompetencyrequirement> msdyn_bookableresourcecategory_msdyn_rolecompetencyrequirement_resourcecategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_rolecompetencyrequirement>("msdyn_bookableresourcecategory_msdyn_rolecompetencyrequirement_resourcecategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_rolecompetencyrequirement_resourcecategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_rolecompetencyrequirement>("msdyn_bookableresourcecategory_msdyn_rolecompetencyrequirement_resourcecategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_rolecompetencyrequirement_resourcecategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_roleutilization_role
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_roleutilization_role")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_roleutilization> msdyn_bookableresourcecategory_msdyn_roleutilization_role
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_roleutilization>("msdyn_bookableresourcecategory_msdyn_roleutilization_role", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_roleutilization_role");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_roleutilization>("msdyn_bookableresourcecategory_msdyn_roleutilization_role", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_roleutilization_role");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_msdyn_timeentry_resourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_timeentry_resourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_timeentry> msdyn_bookableresourcecategory_msdyn_timeentry_resourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_timeentry>("msdyn_bookableresourcecategory_msdyn_timeentry_resourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_timeentry_resourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_timeentry>("msdyn_bookableresourcecategory_msdyn_timeentry_resourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_timeentry_resourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_requirementresourcecategory_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_requirementresourcecategory_ResourceCategory")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_requirementresourcecategory> msdyn_bookableresourcecategory_requirementresourcecategory_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_requirementresourcecategory>("msdyn_bookableresourcecategory_requirementresourcecategory_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_requirementresourcecategory_ResourceCategory");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_requirementresourcecategory>("msdyn_bookableresourcecategory_requirementresourcecategory_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_requirementresourcecategory_ResourceCategory");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcecategory_resourcerequirement
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_resourcerequirement")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_resourcerequirement> msdyn_bookableresourcecategory_resourcerequirement
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_resourcerequirement>("msdyn_bookableresourcecategory_resourcerequirement", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_resourcerequirement");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_resourcerequirement>("msdyn_bookableresourcecategory_resourcerequirement", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_resourcerequirement");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_bookableresourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_bookableresourcecategory")]
		public DLaB.Xrm.Entities.BusinessUnit business_unit_bookableresourcecategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.BusinessUnit>("business_unit_bookableresourcecategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("business_unit_bookableresourcecategory");
				this.SetRelatedEntity<DLaB.Xrm.Entities.BusinessUnit>("business_unit_bookableresourcecategory", null, value);
				this.OnPropertyChanged("business_unit_bookableresourcecategory");
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcecategory_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcecategory_createdby")]
		public DLaB.Xrm.Entities.SystemUser lk_bookableresourcecategory_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_bookableresourcecategory_createdby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_bookableresourcecategory_createdby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_bookableresourcecategory_createdby", null, value);
				this.OnPropertyChanged("lk_bookableresourcecategory_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcecategory_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcecategory_createdonbehalfby")]
		public DLaB.Xrm.Entities.SystemUser lk_bookableresourcecategory_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_bookableresourcecategory_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_bookableresourcecategory_createdonbehalfby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_bookableresourcecategory_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_bookableresourcecategory_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcecategory_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcecategory_modifiedby")]
		public DLaB.Xrm.Entities.SystemUser lk_bookableresourcecategory_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_bookableresourcecategory_modifiedby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_bookableresourcecategory_modifiedby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_bookableresourcecategory_modifiedby", null, value);
				this.OnPropertyChanged("lk_bookableresourcecategory_modifiedby");
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcecategory_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcecategory_modifiedonbehalfby")]
		public DLaB.Xrm.Entities.SystemUser lk_bookableresourcecategory_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_bookableresourcecategory_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_bookableresourcecategory_modifiedonbehalfby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_bookableresourcecategory_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_bookableresourcecategory_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_transactioncategory")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory")]
		public DLaB.Xrm.Entities.msdyn_transactioncategory msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.msdyn_transactioncategory>("msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory");
				this.SetRelatedEntity<DLaB.Xrm.Entities.msdyn_transactioncategory>("msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory", null, value);
				this.OnPropertyChanged("msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory");
			}
		}
		
		/// <summary>
		/// N:1 team_bookableresourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_bookableresourcecategory")]
		public DLaB.Xrm.Entities.Team team_bookableresourcecategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Team>("team_bookableresourcecategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("team_bookableresourcecategory");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Team>("team_bookableresourcecategory", null, value);
				this.OnPropertyChanged("team_bookableresourcecategory");
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_bookableresourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_bookableresourcecategory")]
		public DLaB.Xrm.Entities.TransactionCurrency TransactionCurrency_bookableresourcecategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.TransactionCurrency>("TransactionCurrency_bookableresourcecategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrency_bookableresourcecategory");
				this.SetRelatedEntity<DLaB.Xrm.Entities.TransactionCurrency>("TransactionCurrency_bookableresourcecategory", null, value);
				this.OnPropertyChanged("TransactionCurrency_bookableresourcecategory");
			}
		}
		
		/// <summary>
		/// N:1 user_bookableresourcecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_bookableresourcecategory")]
		public DLaB.Xrm.Entities.SystemUser user_bookableresourcecategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("user_bookableresourcecategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("user_bookableresourcecategory");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("user_bookableresourcecategory", null, value);
				this.OnPropertyChanged("user_bookableresourcecategory");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BookableResourceCategory(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["bookableresourcecategoryid"] = base.Id;
                        break;
                    case "bookableresourcecategoryid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_billingtype")]
		public virtual msdyn_BillingType? msdyn_billingtypeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_BillingType?)(EntityOptionSetEnum.GetEnum(this, "msdyn_billingtype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				msdyn_billingtype = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual BookableResourceCategory_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((BookableResourceCategory_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}