//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum msdyn_rmareceiptState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Specify RMA receipt.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_rmareceipt")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class msdyn_rmareceipt : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_DateReceived = "msdyn_datereceived";
			public const string msdyn_name = "msdyn_name";
			public const string msdyn_Note = "msdyn_note";
			public const string msdyn_ReceivedBy = "msdyn_receivedby";
			public const string msdyn_RMA = "msdyn_rma";
			public const string msdyn_rmareceiptId = "msdyn_rmareceiptid";
			public const string Id = "msdyn_rmareceiptid";
			public const string msdyn_ShipVia = "msdyn_shipvia";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string business_unit_msdyn_rmareceipt = "business_unit_msdyn_rmareceipt";
			public const string lk_msdyn_rmareceipt_createdby = "lk_msdyn_rmareceipt_createdby";
			public const string lk_msdyn_rmareceipt_createdonbehalfby = "lk_msdyn_rmareceipt_createdonbehalfby";
			public const string lk_msdyn_rmareceipt_modifiedby = "lk_msdyn_rmareceipt_modifiedby";
			public const string lk_msdyn_rmareceipt_modifiedonbehalfby = "lk_msdyn_rmareceipt_modifiedonbehalfby";
			public const string msdyn_msdyn_rma_msdyn_rmareceipt_RMA = "msdyn_msdyn_rma_msdyn_rmareceipt_RMA";
			public const string msdyn_msdyn_shipvia_msdyn_rmareceipt_ShipVia = "msdyn_msdyn_shipvia_msdyn_rmareceipt_ShipVia";
			public const string msdyn_systemuser_msdyn_rmareceipt_ReceivedBy = "msdyn_systemuser_msdyn_rmareceipt_ReceivedBy";
			public const string team_msdyn_rmareceipt = "team_msdyn_rmareceipt";
			public const string user_msdyn_rmareceipt = "user_msdyn_rmareceipt";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public msdyn_rmareceipt() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "msdyn_rmareceipt";
		
		public const string PrimaryIdAttribute = "msdyn_rmareceiptid";
		
		public const string PrimaryNameAttribute = "msdyn_name";
		
		public const int EntityTypeCode = 10160;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Shows who created the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Shows the sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_datereceived")]
		public System.Nullable<System.DateTime> msdyn_DateReceived
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_datereceived");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_DateReceived");
				this.SetAttributeValue("msdyn_datereceived", value);
				this.OnPropertyChanged("msdyn_DateReceived");
			}
		}
		
		/// <summary>
		/// Enter the name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_name")]
		public string msdyn_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_name");
				this.SetAttributeValue("msdyn_name", value);
				this.OnPropertyChanged("msdyn_name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_note")]
		public string msdyn_Note
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_note");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Note");
				this.SetAttributeValue("msdyn_note", value);
				this.OnPropertyChanged("msdyn_Note");
			}
		}
		
		/// <summary>
		/// Unique identifier for User associated with RMA Receipt.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_receivedby")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_ReceivedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_receivedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ReceivedBy");
				this.SetAttributeValue("msdyn_receivedby", value);
				this.OnPropertyChanged("msdyn_ReceivedBy");
			}
		}
		
		/// <summary>
		/// Unique identifier for RMA associated with RMA Receipt.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_rma")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_RMA
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_rma");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_RMA");
				this.SetAttributeValue("msdyn_rma", value);
				this.OnPropertyChanged("msdyn_RMA");
			}
		}
		
		/// <summary>
		/// Shows the entity instances.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_rmareceiptid")]
		public System.Nullable<System.Guid> msdyn_rmareceiptId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_rmareceiptid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceiptId");
				this.SetAttributeValue("msdyn_rmareceiptid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("msdyn_rmareceiptId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_rmareceiptid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.msdyn_rmareceiptId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier for Ship Via associated with RMA Receipt.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_shipvia")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_ShipVia
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_shipvia");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ShipVia");
				this.SetAttributeValue("msdyn_shipvia", value);
				this.OnPropertyChanged("msdyn_ShipVia");
			}
		}
		
		/// <summary>
		/// Shows the date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningBusinessUnit");
				this.SetAttributeValue("owningbusinessunit", value);
				this.OnPropertyChanged("OwningBusinessUnit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningTeam");
				this.SetAttributeValue("owningteam", value);
				this.OnPropertyChanged("OwningTeam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// Status of the RMA Receipt
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<DLaB.Xrm.Entities.msdyn_rmareceiptState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((DLaB.Xrm.Entities.msdyn_rmareceiptState)(System.Enum.ToObject(typeof(DLaB.Xrm.Entities.msdyn_rmareceiptState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the RMA Receipt
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Shows the time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_msdyn_rmareceipt_msdyn_rmareceiptproduct_RMAReceipt
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_rmareceipt_msdyn_rmareceiptproduct_RMAReceipt")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_rmareceiptproduct> msdyn_msdyn_rmareceipt_msdyn_rmareceiptproduct_RMAReceipt
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_rmareceiptproduct>("msdyn_msdyn_rmareceipt_msdyn_rmareceiptproduct_RMAReceipt", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_rmareceipt_msdyn_rmareceiptproduct_RMAReceipt");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_rmareceiptproduct>("msdyn_msdyn_rmareceipt_msdyn_rmareceiptproduct_RMAReceipt", null, value);
				this.OnPropertyChanged("msdyn_msdyn_rmareceipt_msdyn_rmareceiptproduct_RMAReceipt");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.ActivityPointer> msdyn_rmareceipt_ActivityPointers
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.ActivityPointer>("msdyn_rmareceipt_ActivityPointers", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_ActivityPointers");
				this.SetRelatedEntities<DLaB.Xrm.Entities.ActivityPointer>("msdyn_rmareceipt_ActivityPointers", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_Annotations")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Annotation> msdyn_rmareceipt_Annotations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Annotation>("msdyn_rmareceipt_Annotations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_Annotations");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Annotation>("msdyn_rmareceipt_Annotations", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_Appointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_Appointments")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Appointment> msdyn_rmareceipt_Appointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Appointment>("msdyn_rmareceipt_Appointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_Appointments");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Appointment>("msdyn_rmareceipt_Appointments", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_Appointments");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.AsyncOperation> msdyn_rmareceipt_AsyncOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.AsyncOperation>("msdyn_rmareceipt_AsyncOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_AsyncOperations");
				this.SetRelatedEntities<DLaB.Xrm.Entities.AsyncOperation>("msdyn_rmareceipt_AsyncOperations", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.BulkDeleteFailure> msdyn_rmareceipt_BulkDeleteFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.BulkDeleteFailure>("msdyn_rmareceipt_BulkDeleteFailures", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_BulkDeleteFailures");
				this.SetRelatedEntities<DLaB.Xrm.Entities.BulkDeleteFailure>("msdyn_rmareceipt_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_connections1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_connections1")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Connection> msdyn_rmareceipt_connections1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Connection>("msdyn_rmareceipt_connections1", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_connections1");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Connection>("msdyn_rmareceipt_connections1", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_connections1");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_connections2
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_connections2")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Connection> msdyn_rmareceipt_connections2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Connection>("msdyn_rmareceipt_connections2", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_connections2");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Connection>("msdyn_rmareceipt_connections2", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_connections2");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.DuplicateRecord> msdyn_rmareceipt_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("msdyn_rmareceipt_DuplicateBaseRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_DuplicateBaseRecord");
				this.SetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("msdyn_rmareceipt_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.DuplicateRecord> msdyn_rmareceipt_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("msdyn_rmareceipt_DuplicateMatchingRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_DuplicateMatchingRecord");
				this.SetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("msdyn_rmareceipt_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_Emails")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Email> msdyn_rmareceipt_Emails
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Email>("msdyn_rmareceipt_Emails", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_Emails");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Email>("msdyn_rmareceipt_Emails", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_Emails");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_Faxes
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_Faxes")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Fax> msdyn_rmareceipt_Faxes
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Fax>("msdyn_rmareceipt_Faxes", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_Faxes");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Fax>("msdyn_rmareceipt_Faxes", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_Faxes");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_Letters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_Letters")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Letter> msdyn_rmareceipt_Letters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Letter>("msdyn_rmareceipt_Letters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_Letters");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Letter>("msdyn_rmareceipt_Letters", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_Letters");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_MailboxTrackingFolders
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_MailboxTrackingFolders")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.MailboxTrackingFolder> msdyn_rmareceipt_MailboxTrackingFolders
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.MailboxTrackingFolder>("msdyn_rmareceipt_MailboxTrackingFolders", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_MailboxTrackingFolders");
				this.SetRelatedEntities<DLaB.Xrm.Entities.MailboxTrackingFolder>("msdyn_rmareceipt_MailboxTrackingFolders", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_MailboxTrackingFolders");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_msdyn_approvals
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_msdyn_approvals")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_approval> msdyn_rmareceipt_msdyn_approvals
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_approval>("msdyn_rmareceipt_msdyn_approvals", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_msdyn_approvals");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_approval>("msdyn_rmareceipt_msdyn_approvals", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_msdyn_approvals");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_msdyn_bookingalerts
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_msdyn_bookingalerts")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_bookingalert> msdyn_rmareceipt_msdyn_bookingalerts
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_bookingalert>("msdyn_rmareceipt_msdyn_bookingalerts", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_msdyn_bookingalerts");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_bookingalert>("msdyn_rmareceipt_msdyn_bookingalerts", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_msdyn_bookingalerts");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_PhoneCalls
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_PhoneCalls")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.PhoneCall> msdyn_rmareceipt_PhoneCalls
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.PhoneCall>("msdyn_rmareceipt_PhoneCalls", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_PhoneCalls");
				this.SetRelatedEntities<DLaB.Xrm.Entities.PhoneCall>("msdyn_rmareceipt_PhoneCalls", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_PhoneCalls");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_PrincipalObjectAttributeAccesses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_PrincipalObjectAttributeAccesses")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess> msdyn_rmareceipt_PrincipalObjectAttributeAccesses
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess>("msdyn_rmareceipt_PrincipalObjectAttributeAccesses", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_PrincipalObjectAttributeAccesses");
				this.SetRelatedEntities<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess>("msdyn_rmareceipt_PrincipalObjectAttributeAccesses", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_PrincipalObjectAttributeAccesses");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_ProcessSession
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_ProcessSession")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.ProcessSession> msdyn_rmareceipt_ProcessSession
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.ProcessSession>("msdyn_rmareceipt_ProcessSession", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_ProcessSession");
				this.SetRelatedEntities<DLaB.Xrm.Entities.ProcessSession>("msdyn_rmareceipt_ProcessSession", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_ProcessSession");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_RecurringAppointmentMasters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_RecurringAppointmentMasters")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.RecurringAppointmentMaster> msdyn_rmareceipt_RecurringAppointmentMasters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.RecurringAppointmentMaster>("msdyn_rmareceipt_RecurringAppointmentMasters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_RecurringAppointmentMasters");
				this.SetRelatedEntities<DLaB.Xrm.Entities.RecurringAppointmentMaster>("msdyn_rmareceipt_RecurringAppointmentMasters", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_RecurringAppointmentMasters");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_ServiceAppointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_ServiceAppointments")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.ServiceAppointment> msdyn_rmareceipt_ServiceAppointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.ServiceAppointment>("msdyn_rmareceipt_ServiceAppointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_ServiceAppointments");
				this.SetRelatedEntities<DLaB.Xrm.Entities.ServiceAppointment>("msdyn_rmareceipt_ServiceAppointments", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_ServiceAppointments");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_SharePointDocumentLocations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_SharePointDocumentLocations")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.SharePointDocumentLocation> msdyn_rmareceipt_SharePointDocumentLocations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.SharePointDocumentLocation>("msdyn_rmareceipt_SharePointDocumentLocations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_SharePointDocumentLocations");
				this.SetRelatedEntities<DLaB.Xrm.Entities.SharePointDocumentLocation>("msdyn_rmareceipt_SharePointDocumentLocations", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_SharePointDocumentLocations");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_SharePointDocuments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_SharePointDocuments")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.SharePointDocument> msdyn_rmareceipt_SharePointDocuments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.SharePointDocument>("msdyn_rmareceipt_SharePointDocuments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_SharePointDocuments");
				this.SetRelatedEntities<DLaB.Xrm.Entities.SharePointDocument>("msdyn_rmareceipt_SharePointDocuments", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_SharePointDocuments");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_SocialActivities
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_SocialActivities")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.SocialActivity> msdyn_rmareceipt_SocialActivities
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.SocialActivity>("msdyn_rmareceipt_SocialActivities", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_SocialActivities");
				this.SetRelatedEntities<DLaB.Xrm.Entities.SocialActivity>("msdyn_rmareceipt_SocialActivities", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_SocialActivities");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_SyncErrors
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_SyncErrors")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.SyncError> msdyn_rmareceipt_SyncErrors
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.SyncError>("msdyn_rmareceipt_SyncErrors", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_SyncErrors");
				this.SetRelatedEntities<DLaB.Xrm.Entities.SyncError>("msdyn_rmareceipt_SyncErrors", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_SyncErrors");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_Tasks
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_Tasks")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Task> msdyn_rmareceipt_Tasks
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Task>("msdyn_rmareceipt_Tasks", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_Tasks");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Task>("msdyn_rmareceipt_Tasks", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_Tasks");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_rmareceipt_UserEntityInstanceDatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_rmareceipt_UserEntityInstanceDatas")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.UserEntityInstanceData> msdyn_rmareceipt_UserEntityInstanceDatas
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.UserEntityInstanceData>("msdyn_rmareceipt_UserEntityInstanceDatas", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_rmareceipt_UserEntityInstanceDatas");
				this.SetRelatedEntities<DLaB.Xrm.Entities.UserEntityInstanceData>("msdyn_rmareceipt_UserEntityInstanceDatas", null, value);
				this.OnPropertyChanged("msdyn_rmareceipt_UserEntityInstanceDatas");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_msdyn_rmareceipt
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_msdyn_rmareceipt")]
		public DLaB.Xrm.Entities.BusinessUnit business_unit_msdyn_rmareceipt
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.BusinessUnit>("business_unit_msdyn_rmareceipt", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("business_unit_msdyn_rmareceipt");
				this.SetRelatedEntity<DLaB.Xrm.Entities.BusinessUnit>("business_unit_msdyn_rmareceipt", null, value);
				this.OnPropertyChanged("business_unit_msdyn_rmareceipt");
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_rmareceipt_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_rmareceipt_createdby")]
		public DLaB.Xrm.Entities.SystemUser lk_msdyn_rmareceipt_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_rmareceipt_createdby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_msdyn_rmareceipt_createdby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_rmareceipt_createdby", null, value);
				this.OnPropertyChanged("lk_msdyn_rmareceipt_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_rmareceipt_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_rmareceipt_createdonbehalfby")]
		public DLaB.Xrm.Entities.SystemUser lk_msdyn_rmareceipt_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_rmareceipt_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_msdyn_rmareceipt_createdonbehalfby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_rmareceipt_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_msdyn_rmareceipt_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_rmareceipt_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_rmareceipt_modifiedby")]
		public DLaB.Xrm.Entities.SystemUser lk_msdyn_rmareceipt_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_rmareceipt_modifiedby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_msdyn_rmareceipt_modifiedby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_rmareceipt_modifiedby", null, value);
				this.OnPropertyChanged("lk_msdyn_rmareceipt_modifiedby");
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_rmareceipt_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_rmareceipt_modifiedonbehalfby")]
		public DLaB.Xrm.Entities.SystemUser lk_msdyn_rmareceipt_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_rmareceipt_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_msdyn_rmareceipt_modifiedonbehalfby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_rmareceipt_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_msdyn_rmareceipt_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_rma_msdyn_rmareceipt_RMA
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_rma")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_rma_msdyn_rmareceipt_RMA")]
		public DLaB.Xrm.Entities.msdyn_rma msdyn_msdyn_rma_msdyn_rmareceipt_RMA
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.msdyn_rma>("msdyn_msdyn_rma_msdyn_rmareceipt_RMA", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_rma_msdyn_rmareceipt_RMA");
				this.SetRelatedEntity<DLaB.Xrm.Entities.msdyn_rma>("msdyn_msdyn_rma_msdyn_rmareceipt_RMA", null, value);
				this.OnPropertyChanged("msdyn_msdyn_rma_msdyn_rmareceipt_RMA");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_shipvia_msdyn_rmareceipt_ShipVia
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_shipvia")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_shipvia_msdyn_rmareceipt_ShipVia")]
		public DLaB.Xrm.Entities.msdyn_shipvia msdyn_msdyn_shipvia_msdyn_rmareceipt_ShipVia
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.msdyn_shipvia>("msdyn_msdyn_shipvia_msdyn_rmareceipt_ShipVia", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_shipvia_msdyn_rmareceipt_ShipVia");
				this.SetRelatedEntity<DLaB.Xrm.Entities.msdyn_shipvia>("msdyn_msdyn_shipvia_msdyn_rmareceipt_ShipVia", null, value);
				this.OnPropertyChanged("msdyn_msdyn_shipvia_msdyn_rmareceipt_ShipVia");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_systemuser_msdyn_rmareceipt_ReceivedBy
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_receivedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_systemuser_msdyn_rmareceipt_ReceivedBy")]
		public DLaB.Xrm.Entities.SystemUser msdyn_systemuser_msdyn_rmareceipt_ReceivedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("msdyn_systemuser_msdyn_rmareceipt_ReceivedBy", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_systemuser_msdyn_rmareceipt_ReceivedBy");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("msdyn_systemuser_msdyn_rmareceipt_ReceivedBy", null, value);
				this.OnPropertyChanged("msdyn_systemuser_msdyn_rmareceipt_ReceivedBy");
			}
		}
		
		/// <summary>
		/// N:1 team_msdyn_rmareceipt
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_msdyn_rmareceipt")]
		public DLaB.Xrm.Entities.Team team_msdyn_rmareceipt
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Team>("team_msdyn_rmareceipt", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("team_msdyn_rmareceipt");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Team>("team_msdyn_rmareceipt", null, value);
				this.OnPropertyChanged("team_msdyn_rmareceipt");
			}
		}
		
		/// <summary>
		/// N:1 user_msdyn_rmareceipt
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_msdyn_rmareceipt")]
		public DLaB.Xrm.Entities.SystemUser user_msdyn_rmareceipt
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("user_msdyn_rmareceipt", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("user_msdyn_rmareceipt");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("user_msdyn_rmareceipt", null, value);
				this.OnPropertyChanged("user_msdyn_rmareceipt");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public msdyn_rmareceipt(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["msdyn_rmareceiptid"] = base.Id;
                        break;
                    case "msdyn_rmareceiptid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual msdyn_rmareceipt_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_rmareceipt_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}