//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum msdyn_orderlinetransactionState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Sales estimate detail of an project contract line.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_orderlinetransaction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class msdyn_orderlinetransaction : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_AccountCustomer = "msdyn_accountcustomer";
			public const string msdyn_AccountingDate = "msdyn_accountingdate";
			public const string msdyn_AccountVendor = "msdyn_accountvendor";
			public const string msdyn_Amount = "msdyn_amount";
			public const string msdyn_amount_after_tax = "msdyn_amount_after_tax";
			public const string msdyn_amount_after_tax_Base = "msdyn_amount_after_tax_base";
			public const string msdyn_amount_Base = "msdyn_amount_base";
			public const string msdyn_AmountMethod = "msdyn_amountmethod";
			public const string msdyn_BasisAmount = "msdyn_basisamount";
			public const string msdyn_basisamount_Base = "msdyn_basisamount_base";
			public const string msdyn_BasisPrice = "msdyn_basisprice";
			public const string msdyn_basisprice_Base = "msdyn_basisprice_base";
			public const string msdyn_BasisQuantity = "msdyn_basisquantity";
			public const string msdyn_BillingType = "msdyn_billingtype";
			public const string msdyn_bookableresource = "msdyn_bookableresource";
			public const string msdyn_ContactCustomer = "msdyn_contactcustomer";
			public const string msdyn_ContactVendor = "msdyn_contactvendor";
			public const string msdyn_CustomerType = "msdyn_customertype";
			public const string msdyn_description = "msdyn_description";
			public const string msdyn_DocumentDate = "msdyn_documentdate";
			public const string msdyn_EndDateTime = "msdyn_enddatetime";
			public const string msdyn_ExchangeRateDate = "msdyn_exchangeratedate";
			public const string msdyn_orderlinetransactionId = "msdyn_orderlinetransactionid";
			public const string Id = "msdyn_orderlinetransactionid";
			public const string msdyn_Origin = "msdyn_origin";
			public const string msdyn_Percent = "msdyn_percent";
			public const string msdyn_Price = "msdyn_price";
			public const string msdyn_price_Base = "msdyn_price_base";
			public const string msdyn_PriceList = "msdyn_pricelist";
			public const string msdyn_Product = "msdyn_product";
			public const string msdyn_Project = "msdyn_project";
			public const string msdyn_Quantity = "msdyn_quantity";
			public const string msdyn_ResourceCategory = "msdyn_resourcecategory";
			public const string msdyn_ResourceOrganizationalUnitId = "msdyn_resourceorganizationalunitid";
			public const string msdyn_SalesContract = "msdyn_salescontract";
			public const string msdyn_SalesContractLine = "msdyn_salescontractline";
			public const string msdyn_StartDateTime = "msdyn_startdatetime";
			public const string msdyn_Task = "msdyn_task";
			public const string msdyn_tax = "msdyn_tax";
			public const string msdyn_tax_Base = "msdyn_tax_base";
			public const string msdyn_TransactionCategory = "msdyn_transactioncategory";
			public const string msdyn_TransactionClassification = "msdyn_transactionclassification";
			public const string msdyn_TransactionTypeCode = "msdyn_transactiontypecode";
			public const string msdyn_Unit = "msdyn_unit";
			public const string msdyn_UnitSchedule = "msdyn_unitschedule";
			public const string msdyn_VendorType = "msdyn_vendortype";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string business_unit_msdyn_orderlinetransaction = "business_unit_msdyn_orderlinetransaction";
			public const string lk_msdyn_orderlinetransaction_createdby = "lk_msdyn_orderlinetransaction_createdby";
			public const string lk_msdyn_orderlinetransaction_createdonbehalfby = "lk_msdyn_orderlinetransaction_createdonbehalfby";
			public const string lk_msdyn_orderlinetransaction_modifiedby = "lk_msdyn_orderlinetransaction_modifiedby";
			public const string lk_msdyn_orderlinetransaction_modifiedonbehalfby = "lk_msdyn_orderlinetransaction_modifiedonbehalfby";
			public const string msdyn_account_msdyn_orderlinetransaction_AccountCustomer = "msdyn_account_msdyn_orderlinetransaction_AccountCustomer";
			public const string msdyn_account_msdyn_orderlinetransaction_AccountVendor = "msdyn_account_msdyn_orderlinetransaction_AccountVendor";
			public const string msdyn_bookableresource_msdyn_orderlinetransaction_bookableresource = "msdyn_bookableresource_msdyn_orderlinetransaction_bookableresource";
			public const string msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory = "msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory";
			public const string msdyn_contact_msdyn_orderlinetransaction_ContactCustomer = "msdyn_contact_msdyn_orderlinetransaction_ContactCustomer";
			public const string msdyn_contact_msdyn_orderlinetransaction_ContactVendor = "msdyn_contact_msdyn_orderlinetransaction_ContactVendor";
			public const string Referencingmsdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin = "msdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin";
			public const string msdyn_msdyn_project_msdyn_orderlinetransaction_Project = "msdyn_msdyn_project_msdyn_orderlinetransaction_Project";
			public const string msdyn_msdyn_projecttask_msdyn_orderlinetransaction_Task = "msdyn_msdyn_projecttask_msdyn_orderlinetransaction_Task";
			public const string msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory = "msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory";
			public const string msdyn_organizationalunit_orderlinetransaction = "msdyn_organizationalunit_orderlinetransaction";
			public const string msdyn_pricelevel_msdyn_orderlinetransaction_PriceList = "msdyn_pricelevel_msdyn_orderlinetransaction_PriceList";
			public const string msdyn_product_msdyn_orderlinetransaction_Product = "msdyn_product_msdyn_orderlinetransaction_Product";
			public const string msdyn_salesorder_msdyn_orderlinetransaction_SalesContract = "msdyn_salesorder_msdyn_orderlinetransaction_SalesContract";
			public const string msdyn_uom_msdyn_orderlinetransaction_Unit = "msdyn_uom_msdyn_orderlinetransaction_Unit";
			public const string msdyn_uomschedule_msdyn_orderlinetransaction_UnitSchedule = "msdyn_uomschedule_msdyn_orderlinetransaction_UnitSchedule";
			public const string team_msdyn_orderlinetransaction = "team_msdyn_orderlinetransaction";
			public const string TransactionCurrency_msdyn_orderlinetransaction = "TransactionCurrency_msdyn_orderlinetransaction";
			public const string user_msdyn_orderlinetransaction = "user_msdyn_orderlinetransaction";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public msdyn_orderlinetransaction() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "msdyn_orderlinetransaction";
		
		public const string PrimaryIdAttribute = "msdyn_orderlinetransactionid";
		
		public const string PrimaryNameAttribute = "msdyn_description";
		
		public const int EntityTypeCode = 10059;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Select the customer who this contract belongs to. 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_accountcustomer")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_AccountCustomer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_accountcustomer");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_AccountCustomer");
				this.SetAttributeValue("msdyn_accountcustomer", value);
				this.OnPropertyChanged("msdyn_AccountCustomer");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_accountingdate")]
		public System.Nullable<System.DateTime> msdyn_AccountingDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_accountingdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_AccountingDate");
				this.SetAttributeValue("msdyn_accountingdate", value);
				this.OnPropertyChanged("msdyn_AccountingDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_accountvendor")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_AccountVendor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_accountvendor");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_AccountVendor");
				this.SetAttributeValue("msdyn_accountvendor", value);
				this.OnPropertyChanged("msdyn_AccountVendor");
			}
		}
		
		/// <summary>
		/// Enter the amount on the project contract line estimate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_amount")]
		public Microsoft.Xrm.Sdk.Money msdyn_Amount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_amount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Amount");
				this.SetAttributeValue("msdyn_amount", value);
				this.OnPropertyChanged("msdyn_Amount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_amount_after_tax")]
		public Microsoft.Xrm.Sdk.Money msdyn_amount_after_tax
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_amount_after_tax");
			}
		}
		
		/// <summary>
		/// Value of the amount_after_tax in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_amount_after_tax_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_amount_after_tax_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_amount_after_tax_base");
			}
		}
		
		/// <summary>
		/// Value of the Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_amount_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_amount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_amount_base");
			}
		}
		
		/// <summary>
		/// Select the amount calculation method used for this project contract estimate line. Valid values are: 
		///0: Multiply Quantity By Price
		///1: Fixed Price
		///2: Multiply Basis Quantity By Price
		///3: Multiply Basis Amount By Percent 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_amountmethod")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_AmountMethod
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_amountmethod");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_AmountMethod");
				this.SetAttributeValue("msdyn_amountmethod", value);
				this.OnPropertyChanged("msdyn_AmountMethod");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_basisamount")]
		public Microsoft.Xrm.Sdk.Money msdyn_BasisAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_basisamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BasisAmount");
				this.SetAttributeValue("msdyn_basisamount", value);
				this.OnPropertyChanged("msdyn_BasisAmount");
			}
		}
		
		/// <summary>
		/// Value of the Basis Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_basisamount_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_basisamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_basisamount_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_basisprice")]
		public Microsoft.Xrm.Sdk.Money msdyn_BasisPrice
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_basisprice");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BasisPrice");
				this.SetAttributeValue("msdyn_basisprice", value);
				this.OnPropertyChanged("msdyn_BasisPrice");
			}
		}
		
		/// <summary>
		/// Value of the Basis Price in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_basisprice_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_basisprice_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_basisprice_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_basisquantity")]
		public System.Nullable<decimal> msdyn_BasisQuantity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_basisquantity");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BasisQuantity");
				this.SetAttributeValue("msdyn_basisquantity", value);
				this.OnPropertyChanged("msdyn_BasisQuantity");
			}
		}
		
		/// <summary>
		/// Select whether this project contract line estimate will be charged to the customer or not. Only chargeable project contract line estimates will add to the invoice total
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_billingtype")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_BillingType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_billingtype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BillingType");
				this.SetAttributeValue("msdyn_billingtype", value);
				this.OnPropertyChanged("msdyn_BillingType");
			}
		}
		
		/// <summary>
		/// Shows the resource.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_bookableresource")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_bookableresource
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_bookableresource");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresource");
				this.SetAttributeValue("msdyn_bookableresource", value);
				this.OnPropertyChanged("msdyn_bookableresource");
			}
		}
		
		/// <summary>
		/// Select the customer contact of this Project Contract.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_contactcustomer")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_ContactCustomer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_contactcustomer");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ContactCustomer");
				this.SetAttributeValue("msdyn_contactcustomer", value);
				this.OnPropertyChanged("msdyn_ContactCustomer");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_contactvendor")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_ContactVendor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_contactvendor");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ContactVendor");
				this.SetAttributeValue("msdyn_contactvendor", value);
				this.OnPropertyChanged("msdyn_ContactVendor");
			}
		}
		
		/// <summary>
		/// Select whether the customer was a account or a contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_customertype")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_CustomerType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_customertype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_CustomerType");
				this.SetAttributeValue("msdyn_customertype", value);
				this.OnPropertyChanged("msdyn_CustomerType");
			}
		}
		
		/// <summary>
		/// Type a description of the project contract line estimate
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_description")]
		public string msdyn_description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_description");
				this.SetAttributeValue("msdyn_description", value);
				this.OnPropertyChanged("msdyn_description");
			}
		}
		
		/// <summary>
		/// Enter the document date.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_documentdate")]
		public System.Nullable<System.DateTime> msdyn_DocumentDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_documentdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_DocumentDate");
				this.SetAttributeValue("msdyn_documentdate", value);
				this.OnPropertyChanged("msdyn_DocumentDate");
			}
		}
		
		/// <summary>
		/// Enter the end date on the project contract line estimate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_enddatetime")]
		public System.Nullable<System.DateTime> msdyn_EndDateTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_enddatetime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_EndDateTime");
				this.SetAttributeValue("msdyn_enddatetime", value);
				this.OnPropertyChanged("msdyn_EndDateTime");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_exchangeratedate")]
		public System.Nullable<System.DateTime> msdyn_ExchangeRateDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_exchangeratedate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ExchangeRateDate");
				this.SetAttributeValue("msdyn_exchangeratedate", value);
				this.OnPropertyChanged("msdyn_ExchangeRateDate");
			}
		}
		
		/// <summary>
		/// Shows the project contract line that this estimate line belongs to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_orderlinetransactionid")]
		public System.Nullable<System.Guid> msdyn_orderlinetransactionId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_orderlinetransactionid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_orderlinetransactionId");
				this.SetAttributeValue("msdyn_orderlinetransactionid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("msdyn_orderlinetransactionId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_orderlinetransactionid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.msdyn_orderlinetransactionId = value;
			}
		}
		
		/// <summary>
		/// Foreign key to the detail line that originated this entry. For example, revenue line points to it's related cost line.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_origin")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Origin
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_origin");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Origin");
				this.SetAttributeValue("msdyn_origin", value);
				this.OnPropertyChanged("msdyn_Origin");
			}
		}
		
		/// <summary>
		/// Relevant when amount calculation method on the Project Contract line transactions is "Multiply basis amount by percent"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_percent")]
		public System.Nullable<decimal> msdyn_Percent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_percent");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Percent");
				this.SetAttributeValue("msdyn_percent", value);
				this.OnPropertyChanged("msdyn_Percent");
			}
		}
		
		/// <summary>
		/// Enter the price on the project contract line estimate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_price")]
		public Microsoft.Xrm.Sdk.Money msdyn_Price
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_price");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Price");
				this.SetAttributeValue("msdyn_price", value);
				this.OnPropertyChanged("msdyn_Price");
			}
		}
		
		/// <summary>
		/// Value of the Price in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_price_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_price_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_price_base");
			}
		}
		
		/// <summary>
		/// Select the price list used for defaulting price on this project contract line estimate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_pricelist")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_PriceList
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_pricelist");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_PriceList");
				this.SetAttributeValue("msdyn_pricelist", value);
				this.OnPropertyChanged("msdyn_PriceList");
			}
		}
		
		/// <summary>
		/// Select the product on this project contract line estimate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_product")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Product
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_product");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Product");
				this.SetAttributeValue("msdyn_product", value);
				this.OnPropertyChanged("msdyn_Product");
			}
		}
		
		/// <summary>
		/// Select the name of the project on the project contract estimate line.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_project")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Project
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_project");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Project");
				this.SetAttributeValue("msdyn_project", value);
				this.OnPropertyChanged("msdyn_Project");
			}
		}
		
		/// <summary>
		/// Enter the quantity of the project contract line estimate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_quantity")]
		public System.Nullable<decimal> msdyn_Quantity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_quantity");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Quantity");
				this.SetAttributeValue("msdyn_quantity", value);
				this.OnPropertyChanged("msdyn_Quantity");
			}
		}
		
		/// <summary>
		/// Select the name of the role that is estimated to perform this work.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourcecategory")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_resourcecategory");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ResourceCategory");
				this.SetAttributeValue("msdyn_resourcecategory", value);
				this.OnPropertyChanged("msdyn_ResourceCategory");
			}
		}
		
		/// <summary>
		/// Select the organizational unit of the resource who is estimated to perform the work.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourceorganizationalunitid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_ResourceOrganizationalUnitId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_resourceorganizationalunitid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ResourceOrganizationalUnitId");
				this.SetAttributeValue("msdyn_resourceorganizationalunitid", value);
				this.OnPropertyChanged("msdyn_ResourceOrganizationalUnitId");
			}
		}
		
		/// <summary>
		/// Select the project contract that this estimate line is for.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_salescontract")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_SalesContract
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_salescontract");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_SalesContract");
				this.SetAttributeValue("msdyn_salescontract", value);
				this.OnPropertyChanged("msdyn_SalesContract");
			}
		}
		
		/// <summary>
		/// Shows the project contract line that this project contract line estimate will be mapped to for operating margin calculations.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_salescontractline")]
		public string msdyn_SalesContractLine
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_salescontractline");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_SalesContractLine");
				this.SetAttributeValue("msdyn_salescontractline", value);
				this.OnPropertyChanged("msdyn_SalesContractLine");
			}
		}
		
		/// <summary>
		/// Enter the estimate start date of the portion of work that is being estimated on the project contract estimate line.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_startdatetime")]
		public System.Nullable<System.DateTime> msdyn_StartDateTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_startdatetime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_StartDateTime");
				this.SetAttributeValue("msdyn_startdatetime", value);
				this.OnPropertyChanged("msdyn_StartDateTime");
			}
		}
		
		/// <summary>
		/// Select the name of the work breakdown structure (WBS) task on the project contract line estimate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_task")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Task
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_task");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Task");
				this.SetAttributeValue("msdyn_task", value);
				this.OnPropertyChanged("msdyn_Task");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_tax")]
		public Microsoft.Xrm.Sdk.Money msdyn_tax
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_tax");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_tax");
				this.SetAttributeValue("msdyn_tax", value);
				this.OnPropertyChanged("msdyn_tax");
			}
		}
		
		/// <summary>
		/// Value of the tax in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_tax_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_tax_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_tax_base");
			}
		}
		
		/// <summary>
		/// Select the transaction category on the project contract line estimate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_transactioncategory")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_TransactionCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_transactioncategory");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TransactionCategory");
				this.SetAttributeValue("msdyn_transactioncategory", value);
				this.OnPropertyChanged("msdyn_TransactionCategory");
			}
		}
		
		/// <summary>
		/// Transaction classification of the Project Contract line transaction
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_transactionclassification")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_TransactionClassification
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_transactionclassification");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TransactionClassification");
				this.SetAttributeValue("msdyn_transactionclassification", value);
				this.OnPropertyChanged("msdyn_TransactionClassification");
			}
		}
		
		/// <summary>
		/// Transaction type of the Project Contract line transaction
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_transactiontypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_TransactionTypeCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_transactiontypecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TransactionTypeCode");
				this.SetAttributeValue("msdyn_transactiontypecode", value);
				this.OnPropertyChanged("msdyn_TransactionTypeCode");
			}
		}
		
		/// <summary>
		/// Select the unit on the project contract line estimate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_unit")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Unit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_unit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Unit");
				this.SetAttributeValue("msdyn_unit", value);
				this.OnPropertyChanged("msdyn_Unit");
			}
		}
		
		/// <summary>
		/// Select the unit schedule of the project contract line estimate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_unitschedule")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_UnitSchedule
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_unitschedule");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_UnitSchedule");
				this.SetAttributeValue("msdyn_unitschedule", value);
				this.OnPropertyChanged("msdyn_UnitSchedule");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_vendortype")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_VendorType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_vendortype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_VendorType");
				this.SetAttributeValue("msdyn_vendortype", value);
				this.OnPropertyChanged("msdyn_VendorType");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningBusinessUnit");
				this.SetAttributeValue("owningbusinessunit", value);
				this.OnPropertyChanged("OwningBusinessUnit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningTeam");
				this.SetAttributeValue("owningteam", value);
				this.OnPropertyChanged("OwningTeam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// Status of the Estimate Details
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<DLaB.Xrm.Entities.msdyn_orderlinetransactionState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((DLaB.Xrm.Entities.msdyn_orderlinetransactionState)(System.Enum.ToObject(typeof(DLaB.Xrm.Entities.msdyn_orderlinetransactionState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Estimate Details
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Shows the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.msdyn_orderlinetransaction> Referencedmsdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.msdyn_orderlinetransaction>("msdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencedmsdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin");
				this.SetRelatedEntities<DLaB.Xrm.Entities.msdyn_orderlinetransaction>("msdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedmsdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_orderlinetransaction_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_orderlinetransaction_Annotations")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Annotation> msdyn_orderlinetransaction_Annotations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Annotation>("msdyn_orderlinetransaction_Annotations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_orderlinetransaction_Annotations");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Annotation>("msdyn_orderlinetransaction_Annotations", null, value);
				this.OnPropertyChanged("msdyn_orderlinetransaction_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_orderlinetransaction_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_orderlinetransaction_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.AsyncOperation> msdyn_orderlinetransaction_AsyncOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.AsyncOperation>("msdyn_orderlinetransaction_AsyncOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_orderlinetransaction_AsyncOperations");
				this.SetRelatedEntities<DLaB.Xrm.Entities.AsyncOperation>("msdyn_orderlinetransaction_AsyncOperations", null, value);
				this.OnPropertyChanged("msdyn_orderlinetransaction_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_orderlinetransaction_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_orderlinetransaction_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.BulkDeleteFailure> msdyn_orderlinetransaction_BulkDeleteFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.BulkDeleteFailure>("msdyn_orderlinetransaction_BulkDeleteFailures", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_orderlinetransaction_BulkDeleteFailures");
				this.SetRelatedEntities<DLaB.Xrm.Entities.BulkDeleteFailure>("msdyn_orderlinetransaction_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("msdyn_orderlinetransaction_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_orderlinetransaction_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_orderlinetransaction_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.DuplicateRecord> msdyn_orderlinetransaction_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("msdyn_orderlinetransaction_DuplicateBaseRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_orderlinetransaction_DuplicateBaseRecord");
				this.SetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("msdyn_orderlinetransaction_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("msdyn_orderlinetransaction_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_orderlinetransaction_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_orderlinetransaction_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.DuplicateRecord> msdyn_orderlinetransaction_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("msdyn_orderlinetransaction_DuplicateMatchingRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_orderlinetransaction_DuplicateMatchingRecord");
				this.SetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("msdyn_orderlinetransaction_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("msdyn_orderlinetransaction_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_orderlinetransaction_MailboxTrackingFolders
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_orderlinetransaction_MailboxTrackingFolders")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.MailboxTrackingFolder> msdyn_orderlinetransaction_MailboxTrackingFolders
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.MailboxTrackingFolder>("msdyn_orderlinetransaction_MailboxTrackingFolders", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_orderlinetransaction_MailboxTrackingFolders");
				this.SetRelatedEntities<DLaB.Xrm.Entities.MailboxTrackingFolder>("msdyn_orderlinetransaction_MailboxTrackingFolders", null, value);
				this.OnPropertyChanged("msdyn_orderlinetransaction_MailboxTrackingFolders");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_orderlinetransaction_PrincipalObjectAttributeAccesses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_orderlinetransaction_PrincipalObjectAttributeAccesses")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess> msdyn_orderlinetransaction_PrincipalObjectAttributeAccesses
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess>("msdyn_orderlinetransaction_PrincipalObjectAttributeAccesses", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_orderlinetransaction_PrincipalObjectAttributeAccesses");
				this.SetRelatedEntities<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess>("msdyn_orderlinetransaction_PrincipalObjectAttributeAccesses", null, value);
				this.OnPropertyChanged("msdyn_orderlinetransaction_PrincipalObjectAttributeAccesses");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_orderlinetransaction_ProcessSession
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_orderlinetransaction_ProcessSession")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.ProcessSession> msdyn_orderlinetransaction_ProcessSession
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.ProcessSession>("msdyn_orderlinetransaction_ProcessSession", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_orderlinetransaction_ProcessSession");
				this.SetRelatedEntities<DLaB.Xrm.Entities.ProcessSession>("msdyn_orderlinetransaction_ProcessSession", null, value);
				this.OnPropertyChanged("msdyn_orderlinetransaction_ProcessSession");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_orderlinetransaction_SyncErrors
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_orderlinetransaction_SyncErrors")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.SyncError> msdyn_orderlinetransaction_SyncErrors
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.SyncError>("msdyn_orderlinetransaction_SyncErrors", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_orderlinetransaction_SyncErrors");
				this.SetRelatedEntities<DLaB.Xrm.Entities.SyncError>("msdyn_orderlinetransaction_SyncErrors", null, value);
				this.OnPropertyChanged("msdyn_orderlinetransaction_SyncErrors");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_orderlinetransaction_UserEntityInstanceDatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_orderlinetransaction_UserEntityInstanceDatas")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.UserEntityInstanceData> msdyn_orderlinetransaction_UserEntityInstanceDatas
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.UserEntityInstanceData>("msdyn_orderlinetransaction_UserEntityInstanceDatas", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_orderlinetransaction_UserEntityInstanceDatas");
				this.SetRelatedEntities<DLaB.Xrm.Entities.UserEntityInstanceData>("msdyn_orderlinetransaction_UserEntityInstanceDatas", null, value);
				this.OnPropertyChanged("msdyn_orderlinetransaction_UserEntityInstanceDatas");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_msdyn_orderlinetransaction
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_msdyn_orderlinetransaction")]
		public DLaB.Xrm.Entities.BusinessUnit business_unit_msdyn_orderlinetransaction
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.BusinessUnit>("business_unit_msdyn_orderlinetransaction", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("business_unit_msdyn_orderlinetransaction");
				this.SetRelatedEntity<DLaB.Xrm.Entities.BusinessUnit>("business_unit_msdyn_orderlinetransaction", null, value);
				this.OnPropertyChanged("business_unit_msdyn_orderlinetransaction");
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_orderlinetransaction_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_orderlinetransaction_createdby")]
		public DLaB.Xrm.Entities.SystemUser lk_msdyn_orderlinetransaction_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_orderlinetransaction_createdby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_msdyn_orderlinetransaction_createdby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_orderlinetransaction_createdby", null, value);
				this.OnPropertyChanged("lk_msdyn_orderlinetransaction_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_orderlinetransaction_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_orderlinetransaction_createdonbehalfby")]
		public DLaB.Xrm.Entities.SystemUser lk_msdyn_orderlinetransaction_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_orderlinetransaction_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_msdyn_orderlinetransaction_createdonbehalfby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_orderlinetransaction_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_msdyn_orderlinetransaction_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_orderlinetransaction_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_orderlinetransaction_modifiedby")]
		public DLaB.Xrm.Entities.SystemUser lk_msdyn_orderlinetransaction_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_orderlinetransaction_modifiedby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_msdyn_orderlinetransaction_modifiedby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_orderlinetransaction_modifiedby", null, value);
				this.OnPropertyChanged("lk_msdyn_orderlinetransaction_modifiedby");
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_orderlinetransaction_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_orderlinetransaction_modifiedonbehalfby")]
		public DLaB.Xrm.Entities.SystemUser lk_msdyn_orderlinetransaction_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_orderlinetransaction_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_msdyn_orderlinetransaction_modifiedonbehalfby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_msdyn_orderlinetransaction_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_msdyn_orderlinetransaction_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_account_msdyn_orderlinetransaction_AccountCustomer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_accountcustomer")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_account_msdyn_orderlinetransaction_AccountCustomer")]
		public DLaB.Xrm.Entities.Account msdyn_account_msdyn_orderlinetransaction_AccountCustomer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Account>("msdyn_account_msdyn_orderlinetransaction_AccountCustomer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_account_msdyn_orderlinetransaction_AccountCustomer");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Account>("msdyn_account_msdyn_orderlinetransaction_AccountCustomer", null, value);
				this.OnPropertyChanged("msdyn_account_msdyn_orderlinetransaction_AccountCustomer");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_account_msdyn_orderlinetransaction_AccountVendor
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_accountvendor")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_account_msdyn_orderlinetransaction_AccountVendor")]
		public DLaB.Xrm.Entities.Account msdyn_account_msdyn_orderlinetransaction_AccountVendor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Account>("msdyn_account_msdyn_orderlinetransaction_AccountVendor", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_account_msdyn_orderlinetransaction_AccountVendor");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Account>("msdyn_account_msdyn_orderlinetransaction_AccountVendor", null, value);
				this.OnPropertyChanged("msdyn_account_msdyn_orderlinetransaction_AccountVendor");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_bookableresource_msdyn_orderlinetransaction_bookableresource
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_bookableresource")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresource_msdyn_orderlinetransaction_bookableresource")]
		public DLaB.Xrm.Entities.BookableResource msdyn_bookableresource_msdyn_orderlinetransaction_bookableresource
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.BookableResource>("msdyn_bookableresource_msdyn_orderlinetransaction_bookableresource", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresource_msdyn_orderlinetransaction_bookableresource");
				this.SetRelatedEntity<DLaB.Xrm.Entities.BookableResource>("msdyn_bookableresource_msdyn_orderlinetransaction_bookableresource", null, value);
				this.OnPropertyChanged("msdyn_bookableresource_msdyn_orderlinetransaction_bookableresource");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourcecategory")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory")]
		public DLaB.Xrm.Entities.BookableResourceCategory msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.BookableResourceCategory>("msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory");
				this.SetRelatedEntity<DLaB.Xrm.Entities.BookableResourceCategory>("msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_msdyn_orderlinetransaction_ResourceCategory");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_contact_msdyn_orderlinetransaction_ContactCustomer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_contactcustomer")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_contact_msdyn_orderlinetransaction_ContactCustomer")]
		public DLaB.Xrm.Entities.Contact msdyn_contact_msdyn_orderlinetransaction_ContactCustomer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Contact>("msdyn_contact_msdyn_orderlinetransaction_ContactCustomer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_contact_msdyn_orderlinetransaction_ContactCustomer");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Contact>("msdyn_contact_msdyn_orderlinetransaction_ContactCustomer", null, value);
				this.OnPropertyChanged("msdyn_contact_msdyn_orderlinetransaction_ContactCustomer");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_contact_msdyn_orderlinetransaction_ContactVendor
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_contactvendor")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_contact_msdyn_orderlinetransaction_ContactVendor")]
		public DLaB.Xrm.Entities.Contact msdyn_contact_msdyn_orderlinetransaction_ContactVendor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Contact>("msdyn_contact_msdyn_orderlinetransaction_ContactVendor", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_contact_msdyn_orderlinetransaction_ContactVendor");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Contact>("msdyn_contact_msdyn_orderlinetransaction_ContactVendor", null, value);
				this.OnPropertyChanged("msdyn_contact_msdyn_orderlinetransaction_ContactVendor");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_origin")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public DLaB.Xrm.Entities.msdyn_orderlinetransaction Referencingmsdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.msdyn_orderlinetransaction>("msdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencingmsdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin");
				this.SetRelatedEntity<DLaB.Xrm.Entities.msdyn_orderlinetransaction>("msdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingmsdyn_msdyn_orderlinetransaction_msdyn_orderlinetransaction_Origin");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_project_msdyn_orderlinetransaction_Project
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_project")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_project_msdyn_orderlinetransaction_Project")]
		public DLaB.Xrm.Entities.msdyn_project msdyn_msdyn_project_msdyn_orderlinetransaction_Project
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.msdyn_project>("msdyn_msdyn_project_msdyn_orderlinetransaction_Project", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_project_msdyn_orderlinetransaction_Project");
				this.SetRelatedEntity<DLaB.Xrm.Entities.msdyn_project>("msdyn_msdyn_project_msdyn_orderlinetransaction_Project", null, value);
				this.OnPropertyChanged("msdyn_msdyn_project_msdyn_orderlinetransaction_Project");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_projecttask_msdyn_orderlinetransaction_Task
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_task")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_projecttask_msdyn_orderlinetransaction_Task")]
		public DLaB.Xrm.Entities.msdyn_projecttask msdyn_msdyn_projecttask_msdyn_orderlinetransaction_Task
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.msdyn_projecttask>("msdyn_msdyn_projecttask_msdyn_orderlinetransaction_Task", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_projecttask_msdyn_orderlinetransaction_Task");
				this.SetRelatedEntity<DLaB.Xrm.Entities.msdyn_projecttask>("msdyn_msdyn_projecttask_msdyn_orderlinetransaction_Task", null, value);
				this.OnPropertyChanged("msdyn_msdyn_projecttask_msdyn_orderlinetransaction_Task");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_transactioncategory")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory")]
		public DLaB.Xrm.Entities.msdyn_transactioncategory msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.msdyn_transactioncategory>("msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory");
				this.SetRelatedEntity<DLaB.Xrm.Entities.msdyn_transactioncategory>("msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory", null, value);
				this.OnPropertyChanged("msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_organizationalunit_orderlinetransaction
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourceorganizationalunitid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_organizationalunit_orderlinetransaction")]
		public DLaB.Xrm.Entities.msdyn_organizationalunit msdyn_organizationalunit_orderlinetransaction
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.msdyn_organizationalunit>("msdyn_organizationalunit_orderlinetransaction", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_organizationalunit_orderlinetransaction");
				this.SetRelatedEntity<DLaB.Xrm.Entities.msdyn_organizationalunit>("msdyn_organizationalunit_orderlinetransaction", null, value);
				this.OnPropertyChanged("msdyn_organizationalunit_orderlinetransaction");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_pricelevel_msdyn_orderlinetransaction_PriceList
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_pricelist")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_pricelevel_msdyn_orderlinetransaction_PriceList")]
		public DLaB.Xrm.Entities.PriceLevel msdyn_pricelevel_msdyn_orderlinetransaction_PriceList
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.PriceLevel>("msdyn_pricelevel_msdyn_orderlinetransaction_PriceList", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_pricelevel_msdyn_orderlinetransaction_PriceList");
				this.SetRelatedEntity<DLaB.Xrm.Entities.PriceLevel>("msdyn_pricelevel_msdyn_orderlinetransaction_PriceList", null, value);
				this.OnPropertyChanged("msdyn_pricelevel_msdyn_orderlinetransaction_PriceList");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_product_msdyn_orderlinetransaction_Product
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_product")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_product_msdyn_orderlinetransaction_Product")]
		public DLaB.Xrm.Entities.Product msdyn_product_msdyn_orderlinetransaction_Product
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Product>("msdyn_product_msdyn_orderlinetransaction_Product", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_product_msdyn_orderlinetransaction_Product");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Product>("msdyn_product_msdyn_orderlinetransaction_Product", null, value);
				this.OnPropertyChanged("msdyn_product_msdyn_orderlinetransaction_Product");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_salesorder_msdyn_orderlinetransaction_SalesContract
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_salescontract")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorder_msdyn_orderlinetransaction_SalesContract")]
		public DLaB.Xrm.Entities.SalesOrder msdyn_salesorder_msdyn_orderlinetransaction_SalesContract
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SalesOrder>("msdyn_salesorder_msdyn_orderlinetransaction_SalesContract", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_salesorder_msdyn_orderlinetransaction_SalesContract");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SalesOrder>("msdyn_salesorder_msdyn_orderlinetransaction_SalesContract", null, value);
				this.OnPropertyChanged("msdyn_salesorder_msdyn_orderlinetransaction_SalesContract");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_uom_msdyn_orderlinetransaction_Unit
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_unit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_uom_msdyn_orderlinetransaction_Unit")]
		public DLaB.Xrm.Entities.UoM msdyn_uom_msdyn_orderlinetransaction_Unit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.UoM>("msdyn_uom_msdyn_orderlinetransaction_Unit", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_uom_msdyn_orderlinetransaction_Unit");
				this.SetRelatedEntity<DLaB.Xrm.Entities.UoM>("msdyn_uom_msdyn_orderlinetransaction_Unit", null, value);
				this.OnPropertyChanged("msdyn_uom_msdyn_orderlinetransaction_Unit");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_uomschedule_msdyn_orderlinetransaction_UnitSchedule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_unitschedule")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_uomschedule_msdyn_orderlinetransaction_UnitSchedule")]
		public DLaB.Xrm.Entities.UoMSchedule msdyn_uomschedule_msdyn_orderlinetransaction_UnitSchedule
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.UoMSchedule>("msdyn_uomschedule_msdyn_orderlinetransaction_UnitSchedule", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_uomschedule_msdyn_orderlinetransaction_UnitSchedule");
				this.SetRelatedEntity<DLaB.Xrm.Entities.UoMSchedule>("msdyn_uomschedule_msdyn_orderlinetransaction_UnitSchedule", null, value);
				this.OnPropertyChanged("msdyn_uomschedule_msdyn_orderlinetransaction_UnitSchedule");
			}
		}
		
		/// <summary>
		/// N:1 team_msdyn_orderlinetransaction
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_msdyn_orderlinetransaction")]
		public DLaB.Xrm.Entities.Team team_msdyn_orderlinetransaction
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Team>("team_msdyn_orderlinetransaction", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("team_msdyn_orderlinetransaction");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Team>("team_msdyn_orderlinetransaction", null, value);
				this.OnPropertyChanged("team_msdyn_orderlinetransaction");
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_msdyn_orderlinetransaction
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_msdyn_orderlinetransaction")]
		public DLaB.Xrm.Entities.TransactionCurrency TransactionCurrency_msdyn_orderlinetransaction
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.TransactionCurrency>("TransactionCurrency_msdyn_orderlinetransaction", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrency_msdyn_orderlinetransaction");
				this.SetRelatedEntity<DLaB.Xrm.Entities.TransactionCurrency>("TransactionCurrency_msdyn_orderlinetransaction", null, value);
				this.OnPropertyChanged("TransactionCurrency_msdyn_orderlinetransaction");
			}
		}
		
		/// <summary>
		/// N:1 user_msdyn_orderlinetransaction
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_msdyn_orderlinetransaction")]
		public DLaB.Xrm.Entities.SystemUser user_msdyn_orderlinetransaction
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("user_msdyn_orderlinetransaction", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("user_msdyn_orderlinetransaction");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("user_msdyn_orderlinetransaction", null, value);
				this.OnPropertyChanged("user_msdyn_orderlinetransaction");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public msdyn_orderlinetransaction(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["msdyn_orderlinetransactionid"] = base.Id;
                        break;
                    case "msdyn_orderlinetransactionid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_amountmethod")]
		public virtual msdyn_AmountMethod? msdyn_AmountMethodEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_AmountMethod?)(EntityOptionSetEnum.GetEnum(this, "msdyn_amountmethod")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				msdyn_AmountMethod = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_billingtype")]
		public virtual msdyn_BillingType? msdyn_BillingTypeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_BillingType?)(EntityOptionSetEnum.GetEnum(this, "msdyn_billingtype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				msdyn_BillingType = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_customertype")]
		public virtual msdyn_PartyType? msdyn_CustomerTypeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_PartyType?)(EntityOptionSetEnum.GetEnum(this, "msdyn_customertype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				msdyn_CustomerType = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_transactionclassification")]
		public virtual msdyn_TransactionClassification? msdyn_TransactionClassificationEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_TransactionClassification?)(EntityOptionSetEnum.GetEnum(this, "msdyn_transactionclassification")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				msdyn_TransactionClassification = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_transactiontypecode")]
		public virtual msdyn_TransactionTypeCode? msdyn_TransactionTypeCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_TransactionTypeCode?)(EntityOptionSetEnum.GetEnum(this, "msdyn_transactiontypecode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				msdyn_TransactionTypeCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_vendortype")]
		public virtual msdyn_PartyType? msdyn_VendorTypeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_PartyType?)(EntityOptionSetEnum.GetEnum(this, "msdyn_vendortype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				msdyn_VendorType = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual msdyn_orderlinetransaction_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_orderlinetransaction_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}